name: Test
on: [push]
jobs:
  test-ubuntu-mac:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: CGO_ENABLED=0 go test -v -mod=vendor ./...
  test-windows:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: set CGO_ENABLED=0 && go test -v -mod=vendor ./...
